[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "arabic-reshaper>=3.0.0",
    "docx>=0.2.4",
    "pandas>=2.3.0",
    "python-bidi>=0.6.6",
    "santos>=1.0.1",
]
